defmodule CinderQueryBugRepro.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:my_resources, primary_key: false) do
      add :is_active, :boolean, null: false
      add :number, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:my_resources)
  end
end